version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
  influxdb:
    image: bitnami/influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    expose:
      - "8086"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_USER=dbuser
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_DB=my_database
      - INFLUXDB_USER_BUCKET=my-bucket
      - INFLUXDB_USER_ORG=cms-tedd
      #- DOCKER_INFLUXDB_INIT_MODE=setup
      #- DOCKER_INFLUXDB_INIT_USERNAME=dbuser
      #- DOCKER_INFLUXDB_INIT_PASSWORD=password
      #- DOCKER_INFLUXDB_INIT_ORG=cms-tedd
      #- DOCKER_INFLUXDB_INIT_BUCKET=my-bucket  
    volumes:
      - influxdb_data:/bitnami/influxdb
      #- influxdb2:/var/lib/influxdb2
      #- ./influxdb/config:/etc/influxdb2
  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  dashboard:
    image: bitnami/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"

    volumes:
      - grafana_data:/opt/bitnami/grafana/data
      #- grafana:/var/lib/grafana
    
  low_voltage:
    image: ghcr.io/cms-tedd-ip2i/low_voltage:0.0.1
    restart: always
    links:
      - mosquitto
    #command: ['python3', 'hmp.py', 'lv_hmp4040', 'mosquitto']
    volumes:
      - low_voltage:/usr/app/low_voltage/
  
  web_server:
    image: ghcr.io/cms-tedd-ip2i/tracker_dcs_web:0.0.1
    restart: always
    environment:
      - APP_USER=cdozen
      - APP_PASSWORD=test
    ports:
      - "8001:8000"
    expose:
      - "8001"
    links:
      - mosquitto
    command: ["uvicorn", "tracker_dcs_web.web_server.app:app", "--host", "0.0.0.0"]
    volumes:
      - web_server:/code

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
#  telegraf.conf:
  grafana_data:
  web_server:
  low_voltage:


