name: Docker-Stack
on:
  push:
    branches: [dev,main]
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
    

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
#  IMAGE_NAME_DUMMY: dummy
#  IMAGE_NAME_LOW_VOLTAGE: low_voltage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to ghcr
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
        - name: Docker compose start mqtt and stack
          run: |
            echo "TRACKER_DCS_INFLUXDB_TOKEN=foobar" > my.env 
            docker compose up -d
            docker compose ps